version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    allow:
      - dependency-type: "direct"
    reviewers:
      - "jp-cruz"
    assignees:
      - "jp-cruz"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    allow:
      - dependency-type: "all"
    reviewers:
      - "jp-cruz"
    assignees:
      - "jp-cruz"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
