name: SAST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  security-events: write
  contents: read

jobs:
  sast:
    uses: LegionForge/dev-rig/.github/workflows/node-sast.yml@dbc782028577aef46e21c674a807efce9b5b9007
    with:
      source-dirs: "src"
    permissions:
      contents: read
      security-events: write
      actions: read
