name: SBOM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sbom:
    uses: LegionForge/dev-rig/.github/workflows/node-sbom.yml@dbc782028577aef46e21c674a807efce9b5b9007
