name: Secret Scanning

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  secrets:
    uses: LegionForge/dev-rig/.github/workflows/secrets.yml@dbc782028577aef46e21c674a807efce9b5b9007
